---
- hosts: webserver3
  remote_user: root
  become: yes
  tasks:
  - name: copy file
    copy: src=file1.txt dest=/var/www/file1.txt
  - name: copy file2
    copy: src=file2.txt  dest=/var/www/file2.txt
